workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
        - app_env_vars  # Add your .env variables to this group in Codemagic UI
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Test App Store Connect Auth
        script: |
          set -e
          set -x
          APP_STORE_CONNECT_ISSUER_ID=$APP_STORE_CONNECT_ISSUER_ID \
          APP_STORE_CONNECT_KEY_IDENTIFIER=$APP_STORE_CONNECT_KEY_IDENTIFIER \
          APP_STORE_CONNECT_PRIVATE_KEY=$APP_STORE_CONNECT_PRIVATE_KEY \
          app-store-connect certificates list --verbose
      - name: Set up provisioning profiles
        script: |
          set -e
          set -x
          APP_STORE_CONNECT_ISSUER_ID=$APP_STORE_CONNECT_ISSUER_ID \
          APP_STORE_CONNECT_KEY_IDENTIFIER=$APP_STORE_CONNECT_KEY_IDENTIFIER \
          APP_STORE_CONNECT_PRIVATE_KEY=$APP_STORE_CONNECT_PRIVATE_KEY \
          app-store-connect fetch-signing-files co.codeminer.circMarketPlace \
            --type IOS_APP_STORE \
            --create --verbose
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Create .env and assets
        script: |
          set -e
          echo "Creating .env file..."
          cat > .env << EOF
          DATABASE_URL=$DATABASE_URL
          JWT_SECRET=$JWT_SECRET
          API_BASE_URL=$API_BASE_URL
          JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
          PAYSTACK_SECRET_KEY=$PAYSTACK_SECRET_KEY
          SSL_KEY_PATH=$SSL_KEY_PATH
          SSL_CERT_PATH=$SSL_CERT_PATH
          EMAIL_USER=$EMAIL_USER
          EMAIL_PASSWORD=$EMAIL_PASSWORD
          SMTP_HOST=$SMTP_HOST
          SMTP_PORT=$SMTP_PORT
          SMTP_SECURE=$SMTP_SECURE
          FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
          FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL
          FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY
          EOF
          echo "Creating mock assets directory..."
          mkdir -p assets/mock/
          echo "Setup complete!"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.2.1 \
            --build-number=26 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - gadesanya9907@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false