// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8VXgkSBKIEPmrFB_5HDa0ULquYLduD0Y',
    appId: '1:629769007375:android:5b89ea7d9fa848e50c0e7a',
    messagingSenderId: '629769007375',
    projectId: 'circ-marketplace',
    storageBucket: 'circ-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX4KniVq_QvTKk19t_WzA0uwyW8FGBaNg',
    appId: '1:629769007375:ios:e34c030854f064440c0e7a',
    messagingSenderId: '629769007375',
    projectId: 'circ-marketplace',
    storageBucket: 'circ-marketplace.firebasestorage.app',
    androidClientId: '629769007375-0llkdcln4ld45v5kg02lf5kc8mp5t5sl.apps.googleusercontent.com',
    iosClientId: '629769007375-eok6r824931f3gskkpqcp9cu9cnkpo00.apps.googleusercontent.com',
    iosBundleId: 'co.codeminer.circMarketPlace',
  );

}